CREATE DATABASE E_COMMERCE;
USE E_COMMERCE;


CREATE TABLE Products (
    Product_ID INT,
    Product_Name VARCHAR(50),
    Category VARCHAR(50),
    Price DECIMAL(10,2)
);

INSERT INTO Products VALUES
(1, 'Laptop', 'Electronics', 75000),
(2, 'Mobile', 'Electronics', 35000),
(3, 'Headphones', 'Accessories', 2500),
(4, 'Smart TV', 'Electronics', 55000),
(5, 'Refrigerator', 'Home Appliances', 45000),
(6, 'Washing Machine', 'Home Appliances', 40000),
(7, 'Gaming PC', 'Electronics', 90000),
(8, 'Tablet', 'Electronics', 30000);

SELECT * FROM PRODUCTS;

SELECT PRODUCT_NAME,PRICE FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 3;

SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(PRODUCT_NAME) FROM PRODUCTS;

SELECT SUM(PRICE) TOTAL_PRICE FROM PRODUCTS;
SELECT SUM(PRICE) TOT_PRIC FROM PRODUCTS WHERE PRICE>50000;

SELECT AVG(PRICE) AVG_PRICE FROM PRODUCTS WHERE Category="Electronics";

SELECT MAX(PRICE) FROM PRODUCTS;

SELECT MIN(PRICE) FROM PRODUCTS;

SELECT CATEGORY,SUM(PRICE) TOT_PRIC FROM PRODUCTS 
WHERE PRICE>30000
GROUP BY CATEGORY;

SELECT CATEGORY,SUM(PRICE) TOT_PRIC FROM PRODUCTS 
GROUP BY CATEGORY;
 
SELECT CATEGORY,SUM(PRICE) TOT_PRICE FROM PRODUCTS
GROUP BY CATEGORY 
HAVING SUM(PRICE)>40000;

SELECT CATEGORY,COUNT(PRICE) TOT_PRICE FROM PRODUCTS
GROUP BY CATEGORY 
HAVING COUNT(PRICE)<5;

